import { Routes } from '@angular/router';
import { LoginPage } from './features/auth/pages/login/login-page';
import { OtpPage } from './features/auth/pages/otp/otp-page';
import { ClientHomePage } from './features/client/home/client-home-page';
import { SalonDetailPage } from './features/client/salon-detail/salon-detail-page';
import { TicketOwnerPage } from './features/client/ticket/ticket-owner-page';
import { TicketDetailPage } from './features/client/ticket-detail/ticket-detail-page';
import { MyTicketsPage } from './features/client/tickets/my-tickets-page';
import { ClientProfilePage } from './features/client/profile/client-profile-page';
import { RelativesPage } from './features/client/relatives/relatives-page';
import { AddRelativePage } from './features/client/relatives/add-relative-page';
import { EditRelativePage } from './features/client/relatives/edit-relative-page';
import { ShopPage } from './features/client/shop/shop-page';
import { ProductDetailPage } from './features/client/shop/product-detail-page';
import { CartPage } from './features/client/shop/cart-page';
import { OrderConfirmationPage } from './features/client/shop/order-confirmation-page';
import { MyOrdersPage } from './features/client/shop/my-orders-page';
import { OrderDetailPage } from './features/client/shop/order-detail-page';
import { NotificationsPage } from './features/client/notifications/notifications-page';
import { CoiffeurHomePage } from './features/coiffeur/home/coiffeur-home-page';
import { CoiffeurTicketsPage } from './features/coiffeur/tickets/coiffeur-tickets-page';
import { CoiffeurNotificationsPage } from './features/coiffeur/notifications/coiffeur-notifications-page';
import { CoiffeurProfilePage } from './features/coiffeur/profile/coiffeur-profile-page';
import { CoiffeurPhotosPage } from './features/coiffeur/photos/coiffeur-photos-page';
import { SettingsPage } from './features/shared/settings/settings-page';
import { HelpSupportPage } from './features/shared/support/help-support-page';
import { OnboardingPage } from './features/onboarding/onboarding-page';
import { NotFoundPage } from './features/shared/not-found/not-found-page';

export const routes: Routes = [
  { path: '', pathMatch: 'full', redirectTo: 'onboarding' },
  { path: 'onboarding', component: OnboardingPage },
  { path: 'auth/login', component: LoginPage },
  { path: 'auth/code', component: OtpPage },
  { path: 'client/home', component: ClientHomePage },
  { path: 'client/salons/:id', component: SalonDetailPage },
  { path: 'client/salons/:id/ticket', component: TicketOwnerPage },
  { path: 'client/tickets', component: MyTicketsPage },
  { path: 'client/tickets/:id', component: TicketDetailPage },
  { path: 'client/profile', component: ClientProfilePage },
  { path: 'client/proches', component: RelativesPage },
  { path: 'client/proches/ajouter', component: AddRelativePage },
  { path: 'client/proches/edit/:id', component: EditRelativePage },
  { path: 'client/boutique', component: ShopPage },
  { path: 'client/boutique/produits/:id', component: ProductDetailPage },
  { path: 'client/boutique/panier', component: CartPage },
  { path: 'client/boutique/commande/confirmation', component: OrderConfirmationPage },
  { path: 'client/boutique/commandes', component: MyOrdersPage },
  { path: 'client/boutique/commandes/:id', component: OrderDetailPage },
  { path: 'client/notifications', component: NotificationsPage },
  { path: 'client/settings', component: SettingsPage },
  { path: 'client/support', component: HelpSupportPage },
  { path: 'coiffeur/home', component: CoiffeurHomePage },
  { path: 'coiffeur/tickets', component: CoiffeurTicketsPage },
  { path: 'coiffeur/notifications', component: CoiffeurNotificationsPage },
  { path: 'coiffeur/profile', component: CoiffeurProfilePage },
  { path: 'coiffeur/settings', component: SettingsPage },
  { path: 'coiffeur/settings/photos', component: CoiffeurPhotosPage },
  { path: 'coiffeur/support', component: HelpSupportPage },
  { path: 'home', pathMatch: 'full', redirectTo: 'auth/login' },
  { path: '404', component: NotFoundPage },
  { path: '**', component: NotFoundPage }
];
